- sites/all/modules/custom/bg/bg.module
I think I prefer pulling out the _bg_set_active_tab_by_title function for readability (of the bg_preprocess_page function), but I'm not really a fan of passing around the 'tabs' array (maybe because it's still somewhat mysterious to me); I'm happy to instead add another `if` block in bg_preprocess_page for the bglink case if you prefer, just let me know.
> Make the 'Links' tab active when viewing a bglink node.

- sites/all/modules/custom/bgpage/bgpage.module
Currently the Info tab on a bglink node points to the bglink node; it should
instead point to the bgpage parent node of the bglink.
> #203 Set the bglink Info tab to point to the link's parent.

- sites/all/modules/custom/bg/bg.features.filter.inc
Currently the 'convert urls' filter runs before the xbbcode filter, so an input bbcode url like `[url=http://www.texasento.net/Pic_Tech.html]Overview[/url]` first gets converted by 'convert urls' to `[url=<a href="http://www.texasento.net/Pic_Tech.html]Overview[/url]">http://www.texasento.net/Pic_Tech.html]Overview[/url]</a>` (or something along those lines) and then things continue going downhill when that gets passed to the xbbcode [url] regex.
> #199 #191 Run the xbbcode filter before the 'convert urls' filter.

- sites/all/modules/custom/bgimage/bgimage.views_default.inc
The thumbnail images returned from advanced search now link to their respective bgimage nodes.
For the record, to change this I went to http://bugguide.test/admin/structure/views/view/advanced_search, then
* clicked on "Content: Image (Image)" under Fields,
* changed "Link image to" to "Content",
* clicked Apply, then clicked Save.
* In the menu under Save chose "Export view",
* diffed the exported view with the existing exported Advanced Search view in bgimage.views_default.inc,
* and updated the existing Advanced Search exported view (there were some minor changes in the diff that weren't included in this patch).
> #165 Link thumbnails in advanced search view.

- sites/all/modules/custom/bgimage/bgimage.module
- sites/all/modules/custom/bugguide/bugguide.module
I can't see images on images tabs locally because they fetch from solr, but the images I add on node 3 look correct in the db and the tabs on those new image pages point to node 3 when they should, so I think it looks good.
> #210 Allow adding images to the root node even though it has no parent.

- sites/all/modules/custom/bgmigrate/bgmigrate.drush.inc
I think that's what we want, and it looks like that's what was intended, just a
copy and paste typo.
> #183 Format user's additional license info as 'f' during migration.

- sites/all/modules/custom/bgimage/bgimage.features.field_instance.inc
- sites/all/modules/custom/bgimage/bgimage.module
A user should be able to view a full size image if either:
* their user role has the 'view fullsize bgimages' permission, or
* they created the image.
As suggested at https://github.com/bugguide/bugguide/issues/50#issuecomment-736978382
this was implemented by modifying the image module's version of
hook_field_formatter_view.
Instead of relying on testing $display['settings']['image_link'] == 'file' as in
the image module, which (as far as I can tell) would require making image_link =
'file' the default setting, we instead test for an entity type of bgimage. That
way we can keep the default image_link setting of '' and make our decisions
about full-size viewing knowing that we're only dealing with a bgimage image -
plus a bgimage node should be the only place where it's possible to get a …
> #50 Provide a link to a full-sized image based on user role.

- sites/all/modules/custom/bgimage/bgimage.module
The database won't necessarily return them in that order - which is the order they need to be in - otherwise.
> #231 Return series images ordered by weight in bgimage_get_series.

- sites/all/modules/custom/bgmap/bgmap.module
- sites/all/modules/custom/bgpage/bgpage.module
The main issue was that the default View/Info tab has a weight of -10, not 0 as one might expect.
> #177 Set the order of tabs to match current Bugguide.

- sites/all/modules/custom/bg/bg.module
- sites/all/modules/custom/bgusers/bgusers.features.user_permission.inc
This reimplements the functionality removed in https://git.drupalcode.org/project/drupal/-/commit/fea12f8c1d4d4d71176b1a877794e1470ca2b63b
See what you think John, I'm certainly not tied to this solution, I'd be happy to drop this and handle the editing comments issue some other way.
Two notes on the reimplementation:
* I dropped the drupal_static code in the "does this comment have replies" code since I don't see that function ever being called more than once on a page load for the same comment [please correct me though if I'm misunderstanding how that works and you think maybe it could be called more than once];
* I changed the original 'count' query to an exists query; exists is all we care about, and I'd like to believe this: …
> Allow users to edit their own comments

- sites/all/modules/custom/bgimage/bgimage.module
- sites/all/modules/custom/bgimage/bgimage.pages.inc
- sites/all/modules/custom/bgusers/bgusers.features.user_permission.inc
- sites/all/themes/bulmabug/templates/system/block--bgimage--tagged-images.tpl.php
I had to make some small css changes to deal with clipboard buttons overflowing into a second row, so here are some screenshots:
> Implement 'quiet move' functionality for senior editors

- sites/all/modules/custom/bg/bg.module
- sites/all/modules/custom/bgimage/bgimage.module
- sites/all/modules/custom/bglink/bglink.module
- sites/all/modules/custom/bglink/bglink.pages.inc
- sites/all/modules/custom/bgref/bgref.module
- sites/all/modules/custom/bgref/bgref.pages.inc
- sites/all/themes/bulmabug/css/bulma-bug.css
Screenshots of the new buttons:
I checked in the database that the parent field is being set correctly using the new buttons (for bgref/bglink, and bgimage), but something's off with display of books and links - for example a book or ref added on node 5 (with parent 3,4,5) doesn't show up on the book/refs tab on node 5 (where I'd expect it), but it does show up on nodes 3 and 4 (where I wouldn't expect it)...
> Create 'Add book' and 'Add link' buttons for adding new content

- sites/all/modules/custom/bgref/bgref.views_default.inc
To make this change I went to http://bugguide.test/#overlay=admin/structure/views/view/all_books/edit/by_bgpage, clicked on the Books tab, then clicked on Format: Settings, and clicked the radio button for None in the 'Default sort' column, then saved everything, exported the bgref feature, and diffed to find the right line to change and what to change it to.
> #236 Don't sort by the Title column in the bgrefs view.

- sites/all/modules/custom/bgpage/bgpage.module
Currently we're including all refs or links whose parent is strictly above or stricly below the current node.
> #238 Include refs and links whose parent is the current node.

- sites/all/modules/custom/bgpage/bgpage.module
This stopped working after PR #206 since the menu position of the Info tab was/is hard-coded in bgpage_menu_local_tasks_alter.
> #177 Refix the Info tab menu link to point to the parent for a bgimage.

- sites/all/modules/custom/bgmap/bgmap.pages.inc
I wasn't tuned into bgmap yet when I added the other no-node checks in #215; this (bgmap) should be the last one.
> #213 Display 'Page not found' for bgmap tabs on non-existent nodes.

- sites/all/themes/bulmabug/template.php
Locally I tested on pagers on the homepage, on recent images, and on a links tab with multiple pages; I'll have to wait until/if this reaches beta to test some of the other pages that could have pagers.
> #181 Add keyboard shortcuts for pager previous/next page links.

- sites/all/modules/custom/bgimage/bgimage.module
It was being based on whichever image in the series was cloned from, i.e. whichever image the 'Add image of this individual' button was clicked on - so in effect if you cloned off of the second image in a series you were starting a brand new series (consisting of the second image and the new cloned image) which no longer included the first image in the original series.
For the record, no matter which image in the series the 'Add image of this individual' button is clicked on, the new cloned image is always added to the end of the series (not inserted). (If you want to reorder you have to unlink, add to clipboard in the order you want, and then relink.)
> Always base the series of a clone on the original image of the series.

- sites/all/modules/custom/bgimage/bgimage.pages.inc
$node_wrapper->nid has type EntityValueWrapper, not int.
> #122 Take value() of nid in quiet move EntityMetadataWrapper.

- sites/all/modules/custom/bgimage/bgimage.strongarm.inc
Users can now edit their own comments, so preview isn't required.
> #219 Set comments on images to 'Preview optional'.

- sites/all/themes/bulmabug/css/bulma-bug.css
The label is too long to fit in the fixed-width grid box, so instead we override bulma's CSS for text inputs in node forms on large screens to display the label and input the same way it would appear on a narrower screen (or in the admin theme): with the label on the line above the input, with no space in between.
> #265 Don't use grid for the County label in the image submission form.

- sites/all/themes/bulma/css/bulma-custom.css
Copied these classes from system.theme.css, with the color changed from 'red' to the border color used for drupal_set_message errors, which (as currently used) is defined by system.theme.css.
I think this covers our current use cases, but it doesn't work on checkboxes or radio inputs (which I guess are difficult to style).
> #324 Define the 'error' class for use in form error reporting.

- sites/all/modules/custom/bguserfields/bguserfields.module
I've tried to duplicate the current BugGuide behavior here, which as far as I can tell is:
* if form submission fails because the username or email is already taken, then give the user another try;
* otherwise redirect to the help page (which doesn't exist on bg7 yet), I guess to make it harder for bots to try again?
Unfortunately this means we have to try to check the error messages set by the system to detect why system validation failed (this will probably need more work if we ever translate to other languages).
The redirect will currently 404 since we don't have a /help page yet.
Note that we set the title on the 'Site' field using the placeholder attribute, following the practice of the other fields on this form, but then also set an invisible actual title because of …
> #335 Check for a living being on the user register form.

- sites/all/themes/bulma/template.php
See https://github.com/bugguide/bugguide/blob/main/includes/form.inc#L1452-L1462
// Although discouraged, a #title is not mandatory for form elements. In
// case there is no #title, we cannot set a form error message.
// Instead of setting no #title, form constructors are encouraged to set
// #title_display to 'invisible' to improve accessibility.
Without the title, when form.inc would set an error on a required field because it was empty, no error message would be set; this affected /user/register and /user/password.
> #326 Set an invisible title on user registration form fields.

- sites/all/modules/custom/bgimage/bgimage.module
node_clone has already set the title by the time our alter hook gets called: https://github.com/bugguide/bugguide/blob/5030d564dd347b44422b0876fe8deb4f8e4f8d1f/sites/all/modules/node_clone/clone.pages.inc#L176-L179 so we just need to set the title again after we've updated it.
> #341 Don't show 'Clone of' in the title of cloned nodes.

- sites/all/modules/custom/bgimage/bgimage.module
Without this patch if you clone an image with an empty date, the current date is inserted in the date field of the cloned node create node form.
The cloned node in this case correctly has an empty field_bgimage_date, but it seems the form creation code in the clone case inserts a default date in that case (I'm not sure why it only happens on cloned nodes and not when editing an existing node with no date field set; maybe just using a different form generation path in the two cases?). The #default_value being set here is the same as that seen on the edit form of an existing node with no date set.
> #281 Honor an empty date when creating a cloned image.

- sites/all/modules/custom/bgpage/bgpage.module
The form 'title' input is intentionally hidden: https://github.com/bugguide/bugguide/blob/0a6766d242f5029934a49ea8e8eb4368fed63bf7/sites/all/modules/custom/bgpage/bgpage.module#L238-L241 since we're going to set it by hand to what we want at the end of the validator (after the issue we're fixing here occurs).
This patch also validates that a common name is set if this is a No Taxon node.
> #358 Use the correct title when checking for existing guide pages.

- .tugboat/initialnodes.php
Currently nodes 4 and 5 created on a local build by .tugboat/initialnodes.php don't have scientific names, which I think means they wouldn't correspond to nodes created by BugGuide; let's make them legit for testing.
> #363 Give initialnodes.php nodes scientific names

- sites/all/modules/custom/bg/bg.module
Sanity check: any variable-substituted string in t() is check_plain'ed, as $submitter is here.
Feel free to change any of the formats (oops, I wound up removing the period at the end of the bglink link, ignore that please):
> #347 Format the 'Works cited' citations based on their type.

- sites/all/modules/custom/bg/bg.module
If the author is 'Jones, J.' we don't want it to be displayed as 'Jones, J.. 1943.'  rtrim would be preferable here, but that could remove entire ellipses if there were, say, a list of 'Author1, Author2, ...' (not that it should actually be written that way...).
> #357 Account for an existing period at the end of Works Cited fields

- sites/all/modules/custom/bg/bg.module
- sites/all/modules/custom/bgpage/bgpage.ds.field.inc
I think this is a bit of a hack since we're working around drupal_set_title by setting the title directly on the page template's $variables; we may just be lucky that template_process_page checks if $variables['title'] is already set before setting it using drupal_get_title: https://github.com/bugguide/bugguide/blob/0a6766d242f5029934a49ea8e8eb4368fed63bf7/includes/theme.inc#L2731-L2741
> #353,#356 Italicize scientific names in node titles and browse links

- sites/all/modules/custom/bg/bg.features.field_instance.inc
We export node-forum-body in order to save the setting to turn off its summary; we also in this case explicitly set the text format option on that field to 'f' only (note that this restriction applies to admin in addition to other users).
> #348 Disable the 'summary' option on forum topic body fields

- .tugboat/initialnodes.php
- sites/all/modules/custom/bg/bg.module
- sites/all/modules/custom/bugguide/bugguide.install
This seems to do what we want: it includes bgimages, bgpages, book refs, and links, but not forum topics or pages.
In bugguide.install, where I changed the Recent pointer, ID Request points to /node/6/bgimage, but if I go to beta, ID Request points to id-request, so not sure if there's some other mechanism that will need to be updated for this to take effect on beta.
(Also locally I see extra stuff (a footer?) at the bottom of the /node page:
I don't see that at node/ on beta, which is what we want; I assume that will continue to be the case on beta.)
> Point the 'Recent' menu item to node/

- sites/all/modules/custom/bgimage/bgimage.module
When you first edit an image node that already has an image, or after you've uploaded an image the user selected, the upload/extract button doesn't exist, instead there's a 'Remove' button.
Otherwise the upload button exists and this code using the '#states' value seems to do what we want by only making the button visible when the value of the file input is not '', i.e. visible only when a file has been selected.
[The #states notation '!value' => '' means "value != ''".]
> #401 Hide the 'Extract image data' button unless an image is selected.
